### ISSUE TITLE
Design: Performance, StaticArrays and the allocate_result pattern

### ISSUE THREAD

**Issue by Affie** [JuliaManifolds/LieGroups.jl#5]
Currently in Manifolds.jl the pattern mostly follows a non-mutating function calling the mutating versions with allocate results.

```julia
function fun(M, x)
    y = allocate_results(M, x)
    return fun!(M, y, x)
end
```

The best performance we could get so far was to use StaticArrays with zero allocations in hot loops. 
There are specific optimizations implemented for use cases we had (for [example](https://github.com/JuliaManifolds/Manifolds.jl/blob/43b699062d9d3ad8fb1b39ad0805c1cbdb2da1e4/src/manifolds/GeneralUnitaryMatrices.jl#L245-L256)) but we can't always get down to zero allocations and it seems to have extra maintenance. 

I would just like to open the discussion and highlight the importance on ways to get to zero allocations.

**Comment by kellertuer** [comment]
Yes, this is a very important example. I would consider the default you mention (allocating function that allocates and calls the mutating one) a very reasonable default – for ciritical parts one should always aim to sue the mutating variant directly of course.
I would consider the allocating variant more the “get started” variant that should make things easy to use (at the cost that it allocates)

We also continue to never type p and X if possible in order to allow StaticArrays to be used.
And sure for each and every function we implement on a concrete Lie group I of course love if we could revisit the code and bring down allocations.
Though to be honest, “allocation hunting” is neither my expertise nor my most favourite hobby – together I am sure we can improve a few :)

**Comment by Affie** [comment]
>In the meantime, implementing special non-mutating cases like the one you linked is the only way that I know. We have a lot of methods here so making non-allocating variants for all of them isn't realistic. Feel free to keep reporting the ones that you use in hot loops, we will keep fixing them.

Thanks for the feedback, I will keep reporting them. I tried to help with it before if you remember, but couldn't quite figure out all the bits that were needed and you still had to do most of the work. One area where I particularly struggle in Manifolds is the trait macros.

Perhaps it will help to develop a developer guide over time with steps that has to be checked off with details such as: run the formatter, put tests here, add docstrings like this, add these traits.

Also, will a pattern like this keep maintain the performance (modified code I lined)?

```julia
# 1 make sure the inner function has zero allocations when called with SMatrix
function Base.exp(M::GeneralUnitaryMatrices{TypeParameter{Tuple{3}},ℝ}, p, X, t::Real)
    θ = abs(t) * norm(M, p, X) / sqrt(2)
    if θ ≈ 0
        a = 1 - θ^2 / 6
        b = θ / 2
    else
        a = sin(θ) / θ
        b = (1 - cos(θ)) / θ^2
    end
    pinvq = I + a .* t .* X .+ b .* t^2 .* (X^2)
    return p * pinvq
end

# 2 then use the inner function to define the mutating function
exp!(M::GeneralUnitaryMatrices{TypeParameter{Tuple{3}},ℝ}, q, p, X, t::Real) = copyto!(q, exp(M, p, X, t))
```
I know it's not always possible, but will at least help to reduce code maintenance.

**Comment by Affie** [comment]
> Could you post an example where it looks impossible to get down to zero allocations?

Will do when I look at it again, I still find it to be a bit black magic.

**Comment by mateuszbaran** [comment]
> > 
> 
> Thanks for the feedback, I will keep reporting them. I tried to help with it before if you remember, but couldn't quite figure out all the bits that were needed and you still had to do most of the work. One area where I particularly struggle in Manifolds is the trait macros.

Yes, I appreciate your help. I am aware that our code is quite convoluted. That's a result of prioritizing nice "casual" user interface, generic operations and performance at the same time.

We generally don't develop the trait system any further than it is now, and I'd prefer to cut out a couple of areas it handles. Unfortunately, it tends to be difficult and always comes at a cost of having complex implicit logic in dispatch (instead of a semi-explicit trait system).

As a tip, I generally avoid looking at the trait dispatch as much as it's possible. Using a debugger to get to the right method works the best for me most of the time. And adding specific methods to avoid problematic trait dispatch is an acceptable solution IMO.

> Perhaps it will help to develop a developer guide over time with steps that has to be checked off with details such as: run the formatter, put tests here, add docstrings like this, add these traits.

Good idea, I think we should add that. @kellertuer maybe it's worth making a separate issue in Manifolds.jl?

> Also, will a pattern like this maintain the performance (modified code I linked)?

> I know it's not always possible, but will at least help to reduce code maintenance.

We've considered that pattern but it slows down the mutating case. There is now an unavoidable allocation, and some broadcast fusion SIMD optimizations are no longer possible. We generally follow a pattern where hot loops only use the mutating variant and all variables are preallocated. I've noticed that it doesn't work well with the common `Array`-of-`SArray`s pattern but we've designed solutions for this problem: nested replacing power manifold and HybridArrays.jl.

I think switching to your pattern would actually significantly increase the code maintenance we have to do.

**Comment by kellertuer** [comment]
Oh that sounds good, to provide a developer help somewhere. I can think about it

**Comment by kellertuer** [comment]
Concerning the propose variant to make `exp` the default and not `exp!`, the design idea is as follows

* `exp` is a bit easier to use but (very most probably) allocates at least once for its result. By default this allocates and passes to `exp!`
* `exp!`  should work with as least as allocations possible, since it even has allocated memory for the result, and even can use that for interims values, the hope is to get this to zero (and hence `exp`to. allocation).

This has the advantage, that we only optimise one function (`exp!`).
Switching these two would mean `exp!` always needs an allocation. That would not be nice.

Also: `exp` is considered maybe the more casual one, easier to start with and such, I would recommend using `exp!` whenever performance is critical – and organise the code that multiple calls “reuse” the memory for the result.

**Comment by Affie** [comment]
> We've considered that pattern but it slows down the mutating case. There is now an unavoidable allocation, and some broadcast fusion SIMD optimizations are no longer possible.

Ahh, ok I missed the allocation. Is it from the exp in `copyto!(q, exp(M, p, X, t))` not being inlined?

> We generally follow a pattern where hot loops only use the mutating variant and all variables are preallocated. I've noticed that it doesn't work well with the common Array-of-SArrays pattern but we've designed solutions for this problem: nested replacing power manifold and HybridArrays.jl.

Yes, we use the Array-of-SArrays pattern, it's the fastest I could get it so far. 

I think we can close this issue then, my take aways

- implementing special non-mutating variants on a case by case basis (open issues or PRs)
- try to use the mutating functions
- wait for julia to improve 
    >IMO the best way to non-allocating functions would be having support for stack-allocated non-escaping mutable structs in Julia. I've been hearing about them for a couple of years by now. I don't know how far in the future that feature is but I hope it will be sooner rather than later.

**Comment by kellertuer** [comment]
> Ahh, ok I missed the allocation. Is it from the exp in `copyto!(q, exp(M, p, X, t))` not being inlined?

Yes, and it probably also can't be inlined.

> * try to use the mutating functions

Yes that would be my main recommendation here.

About the docs/contributors I opened https://github.com/JuliaManifolds/Manifolds.jl/issues/750, and by now also linked back to here. But then we can probably close this, yes.

**Comment by mateuszbaran** [comment]
> Ahh, ok I missed the allocation. Is it from the exp in `copyto!(q, exp(M, p, X, t))` not being inlined?

Depends on what type `exp` returns. If it's `SArray`, it should be fine. If it's `MArray`, inlining could fix it. If it's `Array`, Julia currently can't optimize the allocation away.

> * implementing special non-mutating variants on a case by case basis (open issues or PRs)
> * try to use the mutating functions
> * wait for julia to improve

I think these are right take-aways.

**Comment by Affie** [comment]
> Depends on what type exp returns. If it's SArray, it should be fine. If it's MArray, inlining could fix it. If it's Array, Julia currently can't optimize the allocation away.

Ahh, I didn't think further than StaticArrays. Thanks
